type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Event @table {
  user: User!
  name: String!
  eventDate: Date!
  createdAt: Timestamp!
  description: String
  location: String
}

type Participant @table {
  user: User!
  firstName: String!
  lastName: String!
  createdAt: Timestamp!
  email: String
  studentId: String
}

type Attendance @table {
  event: Event!
  participant: Participant!
  attendanceStatus: String!
  createdAt: Timestamp!
  notes: String
}